<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ini</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\[</string>
	<key>foldingStopMarker</key>
	<string>$(?=\[)</string>
	<key>name</key>
	<string>Zend Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*$\n?</string>
			<key>name</key>
			<string>comment.line.semi-colon.zend-config</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.zend-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;==)\s(?:")?([^"]*)(?:")?;?$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeral.zend-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;==)\s(\d+);?$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.zend-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.tm-grammar</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\.(\w+)\s*(=)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.plain.zend-config</string>
	<key>uuid</key>
	<string>1dc2537b-d972-4a8a-87da-99540843cda4</string>
</dict>
</plist>